#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File: tests/scitex_scholar/verify_cites/test__classify.py
# ----------------------------------------
"""Unit tests for scitex_scholar.verify_cites._classify."""
from __future__ import annotations

import pytest

vc_classify = pytest.importorskip("scitex_scholar.verify_cites._classify")
from scitex_scholar.verify_cites._classify import (  # noqa: E402
    classify,
    is_stub_entry,
    title_similarity,
)
from scitex_scholar.verify_cites._model import (  # noqa: E402
    HALLUCINATED,
    STUB,
    UNVERIFIED,
    VERIFIED,
)
from scitex_scholar.verify_cites._resolve import ResolvedRef  # noqa: E402


# --------------------------------------------------------------------------- #
# is_stub_entry
# --------------------------------------------------------------------------- #
def test_is_stub_entry_true_on_pending_journal():
    # Arrange
    entry = {"title": "[Stub] X", "journal": "Pending scitex-scholar metadata lookup"}
    # Act
    result = is_stub_entry(entry)
    # Assert
    assert result is True


def test_is_stub_entry_true_on_autogenerated_note():
    # Arrange
    entry = {"title": "Real", "note": "Auto-generated stub; replace"}
    # Act
    result = is_stub_entry(entry)
    # Assert
    assert result is True


def test_is_stub_entry_true_when_no_title_and_no_identifier():
    # Arrange
    entry = {"title": "", "author": "Y"}
    # Act
    result = is_stub_entry(entry)
    # Assert
    assert result is True


def test_is_stub_entry_false_on_real_entry():
    # Arrange
    entry = {"title": "Real paper", "doi": "10.1/x", "journal": "Nature"}
    # Act
    result = is_stub_entry(entry)
    # Assert
    assert result is False


# --------------------------------------------------------------------------- #
# title_similarity
# --------------------------------------------------------------------------- #
def test_title_similarity_high_for_latex_and_case_variants():
    # Arrange
    a, b = "{CircStat}: A Toolbox", "circstat a toolbox"
    # Act
    sim = title_similarity(a, b)
    # Assert
    assert sim > 0.9


def test_title_similarity_low_for_unrelated_titles():
    # Arrange
    a, b = "apples", "oranges pears"
    # Act
    sim = title_similarity(a, b)
    # Assert
    assert sim < 0.5


# --------------------------------------------------------------------------- #
# classify
# --------------------------------------------------------------------------- #
def test_classify_verified_when_resolved_and_title_matches():
    # Arrange
    entry = {"title": "CircStat A MATLAB Toolbox", "doi": "10.18637/jss.v031.i10"}
    resolved = ResolvedRef(
        title="CircStat: A MATLAB Toolbox for Circular Statistics",
        doi="10.18637/jss.v031.i10",
        source="crossref",
    )
    # Act
    st = classify("Berens2009", entry, resolved, min_confidence=0.6)
    # Assert
    assert st.status == VERIFIED


def test_classify_verified_records_resolver_source():
    # Arrange
    entry = {"title": "CircStat A MATLAB Toolbox", "doi": "10.18637/jss.v031.i10"}
    resolved = ResolvedRef(
        title="CircStat A MATLAB Toolbox", doi="10.1/x", source="crossref"
    )
    # Act
    st = classify("Berens2009", entry, resolved, min_confidence=0.6)
    # Assert
    assert st.resolver_source == "crossref"


def test_classify_unverified_on_weak_title_match():
    # Arrange
    entry = {"title": "Totally different subject", "doi": "10.1/x"}
    resolved = ResolvedRef(
        title="Circular statistics toolbox", doi="10.1/x", source="crossref"
    )
    # Act
    st = classify("K", entry, resolved, min_confidence=0.8)
    # Assert
    assert st.status == UNVERIFIED


def test_classify_stub_short_circuits_without_resolver():
    # Arrange
    entry = {"title": "[Stub] Foo", "journal": "Pending scitex-scholar metadata lookup"}
    # Act
    st = classify("Foo2020", entry, None)
    # Assert
    assert st.status == STUB


def test_classify_hallucinated_when_no_id_and_no_match():
    # Arrange
    entry = {"title": "A fabricated paper", "author": "Nobody"}
    # Act
    st = classify("Fake2099", entry, None)
    # Assert
    assert st.status == HALLUCINATED


def test_classify_unverified_when_id_present_but_unresolved():
    # Arrange: arXiv DOI that a CrossRef-only resolver would 404 on.
    entry = {"title": "Real arXiv preprint", "doi": "10.48550/arxiv.1904.03603"}
    # Act
    st = classify("Arx2019", entry, None)
    # Assert
    assert st.status == UNVERIFIED

# EOF
