#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File: tests/scitex_scholar/verify_cites/test_verify_cites.py
# ----------------------------------------
"""Unit tests for the verify_cites package (no network, no metadata engines)."""
from __future__ import annotations

import json
import os

import pytest

vc = pytest.importorskip("scitex_scholar.verify_cites")
from scitex_scholar.verify_cites._classify import (  # noqa: E402
    classify,
    is_stub_entry,
    title_similarity,
)
from scitex_scholar.verify_cites._model import (  # noqa: E402
    EXIT_CITATION_STUB,
    EXIT_CITATION_UNLINKED,
    EXIT_NO_CITES,
    EXIT_OK,
    HALLUCINATED,
    STUB,
    UNLINKED,
    UNVERIFIED,
    VERIFIED,
    CiteStatus,
)
from scitex_scholar.verify_cites._resolve import ResolvedRef  # noqa: E402
from scitex_scholar.verify_cites._tex import (  # noqa: E402
    extract_cited_keys,
    resolve_compiled_bib,
)


def _fake_resolver(entry):
    """Resolve anything carrying a DOI to a title matching the bib title."""
    if (entry.get("doi") or "").strip():
        return ResolvedRef(title=entry.get("title"), doi=entry["doi"], source="crossref")
    return None


# --------------------------------------------------------------------------- #
# _tex
# --------------------------------------------------------------------------- #
def test_extract_cited_keys_handles_variants_and_comma_lists(tmp_path):
    # Arrange
    tex = tmp_path / "methods.tex"
    tex.write_text(
        r"Text \cite{Aaa2020, Bbb2021} more \citep[see][]{Ccc2019} "
        r"and \textcite{Ddd2018}.",
        encoding="utf-8",
    )
    # Act
    keys = extract_cited_keys(tmp_path)
    # Assert
    assert keys == {"Aaa2020", "Bbb2021", "Ccc2019", "Ddd2018"}


def test_resolve_compiled_bib_follows_symlink(tmp_path):
    # Arrange: mirror the neurovista trap — bib is a symlink to the real target.
    real = tmp_path / "shared" / "real.bib"
    real.parent.mkdir(parents=True)
    real.write_text("@article{X, title={t}}\n", encoding="utf-8")
    contents = tmp_path / "contents"
    contents.mkdir()
    os.symlink(real, contents / "bibliography.bib")
    (contents / "main.tex").write_text(
        r"\bibliography{bibliography}" + "\n", encoding="utf-8"
    )
    # Act
    resolved = resolve_compiled_bib(tmp_path)
    # Assert
    assert resolved == real.resolve()


# --------------------------------------------------------------------------- #
# _classify — is_stub_entry
# --------------------------------------------------------------------------- #
def test_is_stub_entry_true_on_pending_journal():
    # Arrange
    entry = {"title": "[Stub] X", "journal": "Pending scitex-scholar metadata lookup"}
    # Act
    result = is_stub_entry(entry)
    # Assert
    assert result is True


def test_is_stub_entry_true_on_autogenerated_note():
    # Arrange
    entry = {"title": "Real", "note": "Auto-generated stub; replace"}
    # Act
    result = is_stub_entry(entry)
    # Assert
    assert result is True


def test_is_stub_entry_true_when_no_title_and_no_identifier():
    # Arrange
    entry = {"title": "", "author": "Y"}
    # Act
    result = is_stub_entry(entry)
    # Assert
    assert result is True


def test_is_stub_entry_false_on_real_entry():
    # Arrange
    entry = {"title": "Real paper", "doi": "10.1/x", "journal": "Nature"}
    # Act
    result = is_stub_entry(entry)
    # Assert
    assert result is False


# --------------------------------------------------------------------------- #
# _classify — title_similarity
# --------------------------------------------------------------------------- #
def test_title_similarity_high_for_latex_and_case_variants():
    # Arrange
    a, b = "{CircStat}: A Toolbox", "circstat a toolbox"
    # Act
    sim = title_similarity(a, b)
    # Assert
    assert sim > 0.9


def test_title_similarity_low_for_unrelated_titles():
    # Arrange
    a, b = "apples", "oranges pears"
    # Act
    sim = title_similarity(a, b)
    # Assert
    assert sim < 0.5


# --------------------------------------------------------------------------- #
# _classify — classify
# --------------------------------------------------------------------------- #
def test_classify_verified_when_resolved_and_title_matches():
    # Arrange
    entry = {"title": "CircStat A MATLAB Toolbox", "doi": "10.18637/jss.v031.i10"}
    resolved = ResolvedRef(
        title="CircStat: A MATLAB Toolbox for Circular Statistics",
        doi="10.18637/jss.v031.i10",
        source="crossref",
    )
    # Act
    st = classify("Berens2009", entry, resolved, min_confidence=0.6)
    # Assert
    assert st.status == VERIFIED


def test_classify_verified_records_resolver_source():
    # Arrange
    entry = {"title": "CircStat A MATLAB Toolbox", "doi": "10.18637/jss.v031.i10"}
    resolved = ResolvedRef(
        title="CircStat A MATLAB Toolbox", doi="10.1/x", source="crossref"
    )
    # Act
    st = classify("Berens2009", entry, resolved, min_confidence=0.6)
    # Assert
    assert st.resolver_source == "crossref"


def test_classify_unverified_on_weak_title_match():
    # Arrange
    entry = {"title": "Totally different subject", "doi": "10.1/x"}
    resolved = ResolvedRef(
        title="Circular statistics toolbox", doi="10.1/x", source="crossref"
    )
    # Act
    st = classify("K", entry, resolved, min_confidence=0.8)
    # Assert
    assert st.status == UNVERIFIED


def test_classify_stub_short_circuits_without_resolver():
    # Arrange
    entry = {"title": "[Stub] Foo", "journal": "Pending scitex-scholar metadata lookup"}
    # Act
    st = classify("Foo2020", entry, None)
    # Assert
    assert st.status == STUB


def test_classify_hallucinated_when_no_id_and_no_match():
    # Arrange
    entry = {"title": "A fabricated paper", "author": "Nobody"}
    # Act
    st = classify("Fake2099", entry, None)
    # Assert
    assert st.status == HALLUCINATED


def test_classify_unverified_when_id_present_but_unresolved():
    # Arrange: arXiv DOI that a CrossRef-only resolver would 404 on.
    entry = {"title": "Real arXiv preprint", "doi": "10.48550/arxiv.1904.03603"}
    # Act
    st = classify("Arx2019", entry, None)
    # Assert
    assert st.status == UNVERIFIED


# --------------------------------------------------------------------------- #
# _model — clew boundary mapping
# --------------------------------------------------------------------------- #
def test_to_clew_emits_cite_key_kwarg():
    # Arrange
    st = CiteStatus(key="H", status=HALLUCINATED, doi=None)
    # Act
    payload = st.to_clew()
    # Assert
    assert payload["cite_key"] == "H"


def test_to_clew_hallucinated_sets_is_stub_true():
    # Arrange
    st = CiteStatus(key="H", status=HALLUCINATED, doi=None)
    # Act
    payload = st.to_clew()
    # Assert
    assert payload["is_stub"] is True


def test_to_clew_hallucinated_is_not_resolved():
    # Arrange
    st = CiteStatus(key="H", status=HALLUCINATED, doi=None)
    # Act
    payload = st.to_clew()
    # Assert
    assert payload["resolved"] is False


def test_to_clew_verified_is_resolved_and_not_stub():
    # Arrange
    st = CiteStatus(key="V", status=VERIFIED, doi="10.1/x")
    # Act
    payload = st.to_clew()
    # Assert
    assert (payload["resolved"], payload["is_stub"], payload["doi"]) == (True, False, "10.1/x")


def test_to_clew_carries_local_status_in_metadata():
    # Arrange
    st = CiteStatus(key="U", status=UNVERIFIED, doi="10.1/x")
    # Act
    payload = st.to_clew()
    # Assert
    assert payload["metadata"]["local_status"] == UNVERIFIED


def test_to_clew_has_no_status_kwarg():
    # Arrange: clew.add_citation derives status; it must not receive status=.
    st = CiteStatus(key="V", status=VERIFIED, doi="10.1/x")
    # Act
    payload = st.to_clew()
    # Assert
    assert "status" not in payload


# --------------------------------------------------------------------------- #
# _core — end-to-end (injected entries + fake resolver)
# --------------------------------------------------------------------------- #
@pytest.fixture
def e2e(tmp_path):
    """Run verify_cites over a verified + stub + hallucinated mix."""
    entries = {
        "Good2020": {"title": "A real verified paper", "doi": "10.1/good"},
        "Stubby2021": {
            "title": "[Stub] Stubby",
            "journal": "Pending scitex-scholar metadata lookup",
        },
        "Ghost2099": {"title": "A fabricated one", "author": "Nobody"},
    }
    out = tmp_path / "citation_status.json"
    report = vc.verify_cites(
        tmp_path,
        entries=entries,
        cited_keys=["Good2020", "Stubby2021", "Ghost2099"],
        resolver=_fake_resolver,
        out=out,
        min_confidence=0.6,
    )
    return report, out


def test_verify_cites_marks_verified(e2e):
    # Arrange
    report, _ = e2e
    # Act
    verified = report.by_status(VERIFIED)
    # Assert
    assert verified == ["Good2020"]


def test_verify_cites_marks_stub(e2e):
    # Arrange
    report, _ = e2e
    # Act
    stubs = report.by_status(STUB)
    # Assert
    assert stubs == ["Stubby2021"]


def test_verify_cites_marks_hallucinated(e2e):
    # Arrange
    report, _ = e2e
    # Act
    halluc = report.by_status(HALLUCINATED)
    # Assert
    assert halluc == ["Ghost2099"]


def test_verify_cites_writes_sidecar_keyed_by_bibkey(e2e):
    # Arrange
    _, out = e2e
    # Act
    data = json.loads(out.read_text())
    # Assert
    assert set(data) == {"Good2020", "Stubby2021", "Ghost2099"}


def test_verify_cites_sidecar_records_status(e2e):
    # Arrange
    _, out = e2e
    # Act
    data = json.loads(out.read_text())
    # Assert
    assert data["Good2020"]["status"] == VERIFIED


def test_verify_cites_gate_stub_hallucinated_maps_to_14(e2e):
    # Arrange
    report, _ = e2e
    # Act
    rc = vc.compute_exit_code(report, ["stub", "hallucinated"])
    # Assert
    assert rc == EXIT_CITATION_STUB


def test_verify_cites_all_verified_returns_ok(tmp_path):
    # Arrange
    entries = {"A": {"title": "Paper A", "doi": "10.1/a"}}
    report = vc.verify_cites(
        tmp_path, entries=entries, cited_keys=["A"], resolver=_fake_resolver,
        out=tmp_path / "s.json", min_confidence=0.6,
    )
    # Act
    rc = vc.compute_exit_code(report, ["stub", "hallucinated"])
    # Assert
    assert rc == EXIT_OK


def test_verify_cites_cited_but_absent_is_unlinked(tmp_path):
    # Arrange
    report = vc.verify_cites(
        tmp_path, entries={}, cited_keys=["Missing2020"], resolver=_fake_resolver,
        out=tmp_path / "s.json",
    )
    # Act
    unlinked = report.by_status(UNLINKED)
    # Assert
    assert unlinked == ["Missing2020"]


def test_verify_cites_unlinked_gate_maps_to_16(tmp_path):
    # Arrange
    report = vc.verify_cites(
        tmp_path, entries={}, cited_keys=["Missing2020"], resolver=_fake_resolver,
        out=tmp_path / "s.json",
    )
    # Act
    rc = vc.compute_exit_code(report, ["unlinked"])
    # Assert
    assert rc == EXIT_CITATION_UNLINKED


def test_verify_cites_no_cites_exit_code(tmp_path):
    # Arrange
    report = vc.verify_cites(
        tmp_path, entries={}, cited_keys=[], resolver=_fake_resolver,
        out=tmp_path / "s.json",
    )
    # Act
    rc = vc.compute_exit_code(report, ["stub", "hallucinated"])
    # Assert
    assert rc == EXIT_NO_CITES


def test_verify_cites_stub_only_gate_exit_code(tmp_path):
    # Arrange
    entries = {"S": {"title": "[Stub] S", "note": "Auto-generated stub"}}
    report = vc.verify_cites(
        tmp_path, entries=entries, cited_keys=["S"], resolver=_fake_resolver,
        out=tmp_path / "s.json",
    )
    # Act
    rc = vc.compute_exit_code(report, ["stub"])
    # Assert
    assert rc == EXIT_CITATION_STUB


class _FakeClew:
    def __init__(self):
        self.calls = []

    def add_citation(self, **kwargs):
        self.calls.append(kwargs)


def test_push_to_clew_calls_add_citation_per_cite(tmp_path):
    # Arrange
    entries = {"A": {"title": "Paper A", "doi": "10.1/a"}}
    report = vc.verify_cites(
        tmp_path, entries=entries, cited_keys=["A"], resolver=_fake_resolver,
        out=tmp_path / "s.json", min_confidence=0.6,
    )
    fake = _FakeClew()
    # Act
    pushed = vc.push_to_clew(report, clew=fake)
    # Assert
    assert pushed == 1


def test_push_to_clew_passes_cite_key_not_status(tmp_path):
    # Arrange
    entries = {"A": {"title": "Paper A", "doi": "10.1/a"}}
    report = vc.verify_cites(
        tmp_path, entries=entries, cited_keys=["A"], resolver=_fake_resolver,
        out=tmp_path / "s.json", min_confidence=0.6,
    )
    fake = _FakeClew()
    # Act
    vc.push_to_clew(report, clew=fake)
    # Assert
    assert fake.calls[0]["cite_key"] == "A" and "status" not in fake.calls[0]


# EOF
