"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-scholar-bak-20260404' references
in its source tree. Renames or moves in peer standalones (or in the
umbrella's deep-import surface) surface as a hard failure here — not
as a silent ModuleNotFoundError when an end user runs the CLI.
"""
import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex',
    'scitex.browser',
    'scitex.browser.automation',
    'scitex.browser.core',
    'scitex.browser.debugging',
    'scitex.browser.interaction',
    'scitex.browser.pdf',
    'scitex.browser.stealth',
    'scitex.config',
    'scitex.context',
    'scitex.dict',
    'scitex.io',
    'scitex.logging',
    'scitex.notify',
    'scitex.plt',
    'scitex.plt._figrecipe_integration',
    'scitex.utils._email',
    'scitex_scholar',
    'scitex_scholar._utils',
    'scitex_scholar._utils.text',
    'scitex_scholar.auth',
    'scitex_scholar.auth.ScholarAuthManager',
    'scitex_scholar.auth.core.AuthenticationGateway',
    'scitex_scholar.auth.gateway',
    'scitex_scholar.auth.gateway._OpenURLResolver',
    'scitex_scholar.auth.gateway._resolve_functions',
    'scitex_scholar.auth.sso.SSOAutomator',
    'scitex_scholar.browser',
    'scitex_scholar.browser.ScholarBrowserManager',
    'scitex_scholar.browser.utils',
    'scitex_scholar.browser.utils.close_unwanted_pages',
    'scitex_scholar.citation_graph',
    'scitex_scholar.citation_graph.models',
    'scitex_scholar.cli._url_utils',
    'scitex_scholar.cli.open_browser',
    'scitex_scholar.config',
    'scitex_scholar.core',
    'scitex_scholar.core.Paper',
    'scitex_scholar.core.Papers',
    'scitex_scholar.formatting',
    'scitex_scholar.impact_factor',
    'scitex_scholar.impact_factor.ImpactFactorEngine',
    'scitex_scholar.integration.zotero',
    'scitex_scholar.metadata_engines',
    'scitex_scholar.metadata_engines.ScholarEngine',
    'scitex_scholar.metadata_engines.individual',
    'scitex_scholar.metadata_engines.individual.ArXivEngine',
    'scitex_scholar.metadata_engines.individual.CrossRefEngine',
    'scitex_scholar.metadata_engines.individual.OpenAlexEngine',
    'scitex_scholar.metadata_engines.individual.PubMedEngine',
    'scitex_scholar.metadata_engines.individual.SemanticScholarEngine',
    'scitex_scholar.metadata_engines.utils',
    'scitex_scholar.pdf_download',
    'scitex_scholar.pdf_download.ScholarPDFDownloader',
    'scitex_scholar.pdf_download._cli',
    'scitex_scholar.pdf_download.strategies',
    'scitex_scholar.pdf_download.strategies.manual_download_utils',
    'scitex_scholar.pipelines',
    'scitex_scholar.pipelines.ScholarPipelineMetadataSingle',
    'scitex_scholar.pipelines.ScholarPipelineParallel',
    'scitex_scholar.pipelines.ScholarPipelineSearchParallel',
    'scitex_scholar.pipelines.ScholarPipelineSearchSingle',
    'scitex_scholar.pipelines.ScholarPipelineSingle',
    'scitex_scholar.pipelines.SearchQueryParser',
    'scitex_scholar.search_engines.ScholarSearchEngine',
    'scitex_scholar.search_engines.individual.ArXivSearchEngine',
    'scitex_scholar.search_engines.individual.CrossRefSearchEngine',
    'scitex_scholar.search_engines.individual.OpenAlexSearchEngine',
    'scitex_scholar.search_engines.individual.PubMedSearchEngine',
    'scitex_scholar.search_engines.individual.SemanticScholarSearchEngine',
    'scitex_scholar.storage',
    'scitex_scholar.storage.BibTeXHandler',
    'scitex_scholar.storage._DeduplicationManager',
    'scitex_scholar.storage._LibraryManager',
    'scitex_scholar.url_finder.ScholarURLFinder',
    'scitex_scholar.url_finder.translators._core.registry',
    'scitex_scholar.utils.papers_utils',
    'scitex_scholar.zotero',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-scholar-bak-20260404's declared cross-package dependency must succeed."""
    importlib.import_module(module_name)
