"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-scholar' references
in its source tree. Renames or moves in peer standalones (or in the
umbrella's deep-import surface) surface as a hard failure here — not
as a silent ModuleNotFoundError when an end user runs the CLI.
"""
import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex',
    'scitex.config',
    'scitex.context',
    'scitex.dict',
    'scitex.io',
    'scitex.notify',
    'scitex.plt',
    'scitex.utils._email',
    'scitex_browser',
    'scitex_browser.automation',
    'scitex_browser.core',
    'scitex_browser.debugging',
    'scitex_browser.interaction',
    'scitex_browser.pdf',
    'scitex_browser.stealth',
    'scitex_clew',
    'scitex_dev.click_helpers',
    'scitex_io',
    'scitex_logging',
    'scitex_session',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-scholar's declared cross-package dependency must succeed."""
    importlib.import_module(module_name)
