"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-scholar' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""
import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex',
    'scitex.notify',
    'scitex.utils._email',
    'scitex_browser',
    'scitex_browser.automation',
    'scitex_browser.core',
    'scitex_browser.debugging',
    'scitex_browser.interaction',
    'scitex_browser.pdf',
    'scitex_browser.stealth',
    'scitex_clew',
    'scitex_config',
    'scitex_context',
    'scitex_dev',
    'scitex_dev._cli._completion',
    'scitex_dict',
    'scitex_io',
    'scitex_logging',
    'scitex_plt',
    'scitex_session',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-scholar's declared cross-package dependency must succeed."""
    # Arrange
    # Act
    # Assert
    pytest.importorskip(module_name)
